
# This file is automatically generated, you probably don't want to edit this

mapaOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "mapaOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            long = NULL,
            lat = NULL,
            group = NULL,
            medida = NULL, ...) {

            super$initialize(
                package="mapas2",
                name="mapa",
                requiresData=TRUE,
                ...)

            private$..long <- jmvcore::OptionVariable$new(
                "long",
                long)
            private$..lat <- jmvcore::OptionVariable$new(
                "lat",
                lat)
            private$..group <- jmvcore::OptionVariable$new(
                "group",
                group)
            private$..medida <- jmvcore::OptionVariable$new(
                "medida",
                medida)

            self$.addOption(private$..long)
            self$.addOption(private$..lat)
            self$.addOption(private$..group)
            self$.addOption(private$..medida)
        }),
    active = list(
        long = function() private$..long$value,
        lat = function() private$..lat$value,
        group = function() private$..group$value,
        medida = function() private$..medida$value),
    private = list(
        ..long = NA,
        ..lat = NA,
        ..group = NA,
        ..medida = NA)
)

mapaResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "mapaResults",
    inherit = jmvcore::Group,
    active = list(
        text = function() private$.items[["text"]],
        plot = function() private$.items[["plot"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Choropleth Map")
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="text",
                title="Choropleth Map"))
            self$add(jmvcore::Image$new(
                options=options,
                name="plot",
                title="Descriptives Plot",
                width=500,
                height=400,
                renderFun=".plot"))}))

mapaBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "mapaBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "mapas2",
                name = "mapa",
                version = c(1,0,0),
                options = options,
                results = mapaResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE)
        }))

#' Choropleth Map
#'
#' 
#' @param data .
#' @param long .
#' @param lat .
#' @param group .
#' @param medida .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$text} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$plot} \tab \tab \tab \tab \tab an image \cr
#' }
#'
#' @export
mapa <- function(
    data,
    long,
    lat,
    group,
    medida) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("mapa requires jmvcore to be installed (restart may be required)")

    if ( ! missing(long)) long <- jmvcore::resolveQuo(jmvcore::enquo(long))
    if ( ! missing(lat)) lat <- jmvcore::resolveQuo(jmvcore::enquo(lat))
    if ( ! missing(group)) group <- jmvcore::resolveQuo(jmvcore::enquo(group))
    if ( ! missing(medida)) medida <- jmvcore::resolveQuo(jmvcore::enquo(medida))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(long), long, NULL),
            `if`( ! missing(lat), lat, NULL),
            `if`( ! missing(group), group, NULL),
            `if`( ! missing(medida), medida, NULL))


    options <- mapaOptions$new(
        long = long,
        lat = lat,
        group = group,
        medida = medida)

    analysis <- mapaClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

